---

- name: Install curl, locales and apt-transport-https
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - locales
    - apt-transport-https

- name: Configure Locale as en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
