---

- name: Setup the Git repo
  git:
    name: "{{ item.url }}"
    dest: /home/vagrant/"{{ item.dest }}"
    version: master
    update: no
  with_items:
    - { url : 'https://github.com/dev-sec/ansible-os-hardening.git', dest: 'ansible-os-hardening' }
    - { url : 'https://github.com/teacheraio/DevSecOps-Studio.git', dest: 'DevSecOps-Studio' }
    - { url : 'https://github.com/dev-sec/linux-baseline.git', dest: 'linux-baseline.git' }
    - { url : 'https://github.com/dev-sec/cis-docker-benchmark.git', dest: 'cis-docker-benchmark.git' }

- name: Change owner of repos to vagrant
  file:
    dest: /home/vagrant
    owner: vagrant
    group: vagrant
    mode: 0644
    recurse: yes
