---

- name: Setup the Git repo
  git:
    name: "{{ item }}"
    dest: /home/vagrant
    version: master
  with_items:
    - https://github.com/dev-sec/ansible-os-hardening.git
    - https://github.com/teacheraio/DevSecOps-Studio.git
    - https://github.com/dev-sec/linux-baseline.git
    - https://github.com/dev-sec/cis-docker-benchmark.git

- name: Change owner of repos to vagrant
  file:
    dest: /home/vagrant
    owner: vagrant
    group: vagrant
    mode: 0644
    recurse: yes
