---

- name: Install awscli, awsebcli, ansible, ansible-lint
  pip:
    name: "{{ item }}"
  with_items:
    - awscli
    - awsebcli
    - ansible
    - ansible-lint

- name: Install tree package
  apt:
    name: tree
    state: present

- name: Add vagrant user to Docker group
  user:
    name: vagrant
    groups: docker
    append: "yes"

- name: Generate SSH key of vagrant user
  user:
    name: vagrant
    generate_ssh_key: "yes"
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Clone git repos of needed code
  import_tasks: git_repos.yml
