sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

env:
  - PLAYBOOK=devsecops-box
  - PLAYBOOK=jenkins
  - PLAYBOOK=gitlab
  - PLAYBOOK=gitlab-runner
  - PLAYBOOK=elk

services:
  - docker

before_install:
  - sudo apt-get -q update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y docker-ce
  - ssh-keygen -f id_rsa -t rsa -b 4096 -C "your_email@example.com" -N ''

install:
  - pip install ansible==2.2.1.0
  - pip install ansible-lint
  - pip install docker
  - pip install molecule==1.25.0

script:
  - ansible-lint provisioning/$PLAYBOOK.yml
