---
- src: geerlingguy.pip
- src: geerlingguy.ruby
- src: geerlingguy.docker
- src: geerlingguy.ansible-role-packer
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
- src: geerlingguy.kibana
- src: geerlingguy.logstash
- src: secfigo.terraform
- src: rvm_io.ruby
