---

- name: Install ELK stack
  hosts: all
  become: yes

  vars:
    - elasticsearch_network_host: localhost

  roles:
    - common
    - geerlingguy.nginx
    - geerlingguy.elasticsearch
    - geerlingguy.kibana
    - geerlingguy.logstash
