---

- name: Install gitlab runner
  hosts: all
  become: true

  vars:
    gitlab_runner_registration_token: ''
    gitlab_runner_connect_enable: false

  roles:
    - common
    - geerlingguy.docker
    - gitlab-runner
    - geerlingguy.packer
    - secfigo.terraform
    - python
    - cli-tools
  tags:
    - runner
