---

- name: Install gitlab runner
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    gitlab_runner_registration_token: ''
    gitlab_runner_connect_enable: false
  roles:
    - common
    - gitlab-runner
  tags:
    - runner

