---

- name: Configure gitlab on ubuntu server
  hosts: all
  become: true
  become_user: root
  remote_user: root

  vars:
    gitlab_restart_handler_failed_when: false
    gitlab_external_url: https://gitlab.local/
    gitlab_in_docker: true

  roles:
    - common
    - gitlab
