---

- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: false
  when: (gitlab_runner_connect_enable == true)

- name: Upload gitlab runner register script to /tmp
  template:
    src: gitlab-register.sh
    dest: /tmp/gitlab-register.sh
    owner: root
    group: root
    mode: 0754
  when: configured_runners.stderr.find("https://gitlab.local/") == -1

- name: Register gitlab runner
  command: bash /tmp/gitlab-register.sh
  when: (configured_runners.stderr.find("https://gitlab.local/") == -1 ) and (gitlab_runner_connect_enable == true)
