---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  remote_user: vagrant

  vars:
    oracle_java_version: 8

  roles:
    - common
    - java
    - jenkins
    - python
    #- selenium
